# Imagem base para execução da pipeline, que depende de um ambiente Python
image:
  python:latest

# Executa os testes unitários especificados em tests/appTest.py
run_tests:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest -v tests/appTest.py

# Templates do Gitlab para facilitar as etapas de build da imagem Docker, 
# deploy no ECS, SAST com Semgrep, detecção de segredos com Gitleaks e 
# escaneamento de vulnerabilidades no contêiner com Trivy.
include:
  - template: AWS/Deploy-ECS.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml