stages:
  - "deploy"
deploy to s3:
  stage: deploy
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 rm s3://$S3_NAME --recursive
    - aws s3 cp site s3://$S3_NAME --recursive